---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: link
  type: text
  config:
    required: false
  label: Link
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- src/projects/thinktank.md
- src/projects/ta-eye-care.md
