---
label: Project
hide_body: false
fields:
- name: title
  type: text
  config:
    required: false
  label: Title
- name: link
  type: text
  config:
    required: false
  label: Link
- name: date
  type: datetime
  label: Date
  description: ''
  config:
    required: false
    date_format: 
    time_format: 
    display_utc: false
pages:
- src/projects/mcconnell-air-force-base-library.md
- src/projects/mbt-consulting.md
- src/projects/camp-sweeney.md
- src/projects/pattinan-monogramming.md
- src/projects/lake-murray-osprey.md
- src/projects/nail-safari.md
- src/projects/mycambridge.md
- src/projects/ta-eye-care.md
- src/projects/thinktank.md
